### PR TITLE
Implement brand fonts

### PR DESCRIPTION
**Pull request by iamstuartwilson**
## Overview
There's an additional commit on top of the original work here to remove any blocking of drawing the UI before the font has loaded.  Once we resolve the Lambda issues, I'll make a PR to follow this one.

Without the wait to load the font before drawing the UI there will be some FOUT on slow connections.

## Screenshot
image

## Example
Uploaded [here](https://upload.clinicjs.org/private/4af37536e2089becb1e2826e3531b5e53bb5c566a47701fe920e89d86858e09d/1532.clinic-bubbleprof.html). (Needs superuser access)

## Testing
1. Checkout this branch locally
2. Checkout [this Common branch](https://github.com/nearform/node-clinic-common/tree/feature/brand-fonts) and `npm link`
3. `npm run visualize-all ...`

## Todo
 - [x] Merge [this PR](https://github.com/nearform/node-clinic-common/pull/13) and update Common dependency (fixes failing test).

### CODE REVIEW

**Comment by AlanSl** [comment]
There's some issue with the page load timing and this which seems to stop the load indicator from showing and maybe makes it take longer to load overall or reloads something. 

For me, this huge profile (223 mb HTML - might be best to download it! Superuser only) shows a blank screen for a very long time, then a flash of a bubbleprof profile, then a blank screen again:

https://upload.clinicjs.org/private/0694e5edca8959a34042beb84639e49935eb73cf0d9f2b9df21d400043b70968/4831.clinic-bubbleprof.html

Compared to this from Master, where it shows a "Loading file" spinner so the user knows it's a huge file then a drawing spinner:

https://upload.clinicjs.org/private/768ab68d10aeca612b77650789618bfaa4ea4698cb406dcc8ddc363d3d5f84ab/4831.clinic-bubbleprof.html

(testing changes with these huge profiles is a pain - 7078 in the samples repo is hefty enough to see some of this lag without taking minutes to regenerate and reload each time)

**Comment by iamstuartwilson** [comment]
@AlanSl good catch. A hangover from the original implementation that waited for fonts to load and applied a `<body>` class to initially hide the original bootstrap loader.

I've removed this across all PRs which shout squash this bug if you could retest locally 👍

**Comment by AlanSl** [comment]
There's a bit of a strange flash / judder on this one https://upload.clinicjs.org/public/ed4ebc2eda7e8a2220ea087055d44f555a86f9da2d23364884502fb74aa9b726/11082.clinic-bubbleprof.html (if you don't see it, trying refreshing in chrome with shift held down), which seems to be causing a rogue loader to be visible in the thumbnail:

image

**Comment by iamstuartwilson** [comment]
@AlanSl I've updated this PR and the Flame PR to use setTimeout to put font loading at the back of the queue which fixes the juddering to a degree, but does prevent the spinner from showing in the screenshot:

image

[Example](https://upload.clinicjs.org/private/2a90f4e6e0255af261bcbfdb36980d4d0afe38f9de8e45aa386d17a955669fb3/11082.clinic-bubbleprof.html)

**Comment by goto-bus-stop** [comment]
Far as I can tell these PRs work with the current production image lambda, the screenshots just don't use the new fonts. that judder still exists in Bubbleprof only but is acceptable for now imo. Gonna go ahead and get all these PRs in (**finally** lmao).

**Pull request merged**
