### PR TITLE
Show a message and spinner-like animation while opening slow nodes

### PR DESCRIPTION
**Pull request by AlanSl**
WIP because it contains a strange bug where sometimes the changes have been made but the browser seems to not do a redraw before getting tied up doing slow selectNode computations.

- [x] Fix intermittent bug
- [x] Check it's reliable on all supported browsers

Includes @iamstuartwilson 's branch  https://github.com/nearform/node-clinic-bubbleprof/tree/feature/hover-box-loading-state for the CSS animation itself

This adds a message, shows highlighting styles and shows a loading animation when the user selects a node. Normally this is so fast they won't even notice, but in crazy profiles with over 1000 nodes in a node, this can take a long time.

image

Here's an example of one such profile (which also demonstrates the bug, for me clicking on the big node shows the "Expanding...." text, highlight and animation roughly half the time with no obvious pattern as to why - adding console.logs shows that it's not a timing / race, the code is being processed in the right order, it just doesn't always do a redraw as expected): https://upload.clinicjs.org/public/8b846c75fc3f79a92b8152b166a59893411250445c21c51aff23bae0da1e9b8f/1005.clinic-bubbleprof.html

### CODE REVIEW

**Comment by iamstuartwilson** [comment]
@AlanSl I had a look and can't reliably reproduce the intermittent issue I'm afraid. 😞 

Whilst hammering some `console.log()`s I noticed that the hover event listener is being bound twice due to there being multiple instances of the `AreaChart` and so `this.listeningUIs` potentially not working as expected to prevent multiple bindings? https://github.com/nearform/node-clinic-bubbleprof/blob/de1bcb493992973d87e9040b13fea03db24e57fa/visualizer/draw/area-chart.js#L48-L54

**Comment by AlanSl** [comment]
With the latest commits: it works reliably on Chrome and Safari (and now also Firefox). 

On Edge, the animation starts then freezes - this seems to be an issue with recent versions of Edge because the same thing happens to the regular loading spinner now too. There's a visible change, and that's the important thing.

**Comment by AlanSl** [comment]
Tidied up and rebased, and removed a spinner on applying hashes which isn't consistent enough and should be its own PR if done at all.

Re. comment above - good spot on that faulty area chart logic, there's a lot of room for improvement there and it's the next big bottleneck after these fixes for node selection - I've added a separate PR that fixes that and removes a lot of other unnecessary activity - https://github.com/nearform/node-clinic-bubbleprof/pull/302

**Comment by iamstuartwilson** [comment]
Tested locally and looking good to me 👍

**Pull request merged**
